networks:
  reg-to-games:
    external: true
  game-net:

services:

  game-postgresql:
    restart: always
    image: postgres:14
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr, csvlog"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./postgreSQL/create.sql:/docker-entrypoint-initdb.d/create.sql
      #- ./postgreSQL/set.sql:/docker-entrypoint-initdb.d/set.sql
    ports:
      - 5491:5432
    networks:
      - game-net

  games-app:
    build: .
    ports:
      - 8022:8080
    networks:
      - reg-to-games
      - game-net
    depends_on:
      - game-postgresql
    command: ["wait-for-it.sh", "game-postgresql:5432", "--", "/app/bin"]