networks:
  reg-to-games:
    external: true

services:

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - reg-to-games

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    networks:
      - reg-to-games
    depends_on:
      - redis
    command: ["wait-for-it.sh", "redis:6379", "--", "/app/bin"]
