networks:
  reg-to-games:
    external: true
  media-net:

services:

  media-postgresql:
    restart: always
    image: postgres:14
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr, csvlog"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./postgreSQL/create.sql:/docker-entrypoint-initdb.d/create.sql
      #- ./postgreSQL/set.sql:/docker-entrypoint-initdb.d/set.sql
    ports:
      - 5435:5432
    networks:
      - media-net

  media-app:
    build: .
    ports:
      - 8086:8080
    networks:
      - reg-to-games
      - media-net
    depends_on:
      - media-postgresql
    command: ["wait-for-it.sh", "media-postgresql:5432", "--", "/app/bin"]