CREATE TABLE  users
(
    userid bigint NOT NULL DEFAULT 0 PRIMARY KEY,
    name text DEFAULT '',
    lastname text DEFAULT '',
    username text DEFAULT '',
    whence text DEFAULT '',
    language text DEFAULT '',
    useradmin boolean DEFAULT false,
    action text DEFAULT '',
    setupreg text DEFAULT '',
    actionwithmes text DEFAULT 'DEL',
    level integer DEFAULT 0,
    launchpoint integer DEFAULT 0, 
    seats integer DEFAULT 0,
    payment text  DEFAULT '',
    timeinterval text DEFAULT '',
    direction text DEFAULT '',
    mediagoupcounter integer DEFAULT 0,
    changeable text DEFAULT '',
    actgame text DEFAULT '',
    willchangeable text DEFAULT '',
    newpay text DEFAULT '',
    notifgameid integer DEFAULT 0,
    lasttimeuse timestamp without time zone,
    customlanguage boolean DEFAULT false,
    phonenumber bigint DEFAULT 0,
    status integer DEFAULT 1,
    gameid integer DEFAULT 0,
    mediagroupid text DEFAULT '',
    exmessageid integer DEFAULT 0,
    mlimit integer DEFAULT 7
);