services:

  postgresql:
    restart: always
    image: postgres:14
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr, csvlog"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./postgres/createdb.sql:/docker-entrypoint-initdb.d/createdb.sql
    ports:
      - 5431:5432

  app:
    build: .
    ports:
      - 8080:8081
    depends_on:
      - postgresql
    command: ["wait-for-it.sh", "postgresql:5432", "--", "/app/bin"]